version: 1.6.{build}
image: Visual Studio 2017
build_script:
- cmd: pwsh .\Build.ps1
artifacts:
- path: '*.nupkg'
  name: Prototest
  type: NuGetPackage
deploy:
- provider: NuGet
  api_key:
    secure: Gc45A/3+PYem242Xzm2BBTAqrfddZNt85vQ8kq32PguForxZbZpnLcidff7dqI+h
  artifact: '*.nupkg'
  on:
    branch: master