version: 1.6.{build}
image: Visual Studio 2017
build_script:
- cmd: pwsh .\Build.ps1
artifacts:
- path: '*.nupkg'
  name: Prototest
  type: NuGetPackage
deploy:
- provider: NuGet
  api_key:
    secure: 7EBIbpQRH3MfUF5H1SK55bIMzKu6g9ePH2thOhAHUxl938xOtCW7fza1Fc+JoRUN
  artifact: Prototest
  on:
    branch: master